apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-demo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/lranasingha/argocd-demo-apps.git'
    path: '/apps/redis-demo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
